/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DevelopersRouteImport } from './routes/developers'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as EmojiRouteImport } from './routes/emoji'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LicensesRouteImport } from './routes/licenses'
import { Route as LlmsFullDottxtRouteImport } from './routes/llms-full[.]txt'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as OpenapiDotjsonRouteImport } from './routes/openapi[.]json'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as DotwellKnownAgentDotjsonRouteImport } from './routes/[.]well-known.agent[.]json'
import { Route as AuthenticatedImportSearchRouteImport } from './routes/_authenticated/import-search'
import { Route as AuthenticatedImportsRouteImport } from './routes/_authenticated/imports'
import { Route as AuthenticatedMyLibraryRouteImport } from './routes/_authenticated/my-library'
import { Route as AuthenticatedReviewRouteImport } from './routes/_authenticated/review'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as CollectionsIndexRouteImport } from './routes/collections.index'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as GamesSlugRouteImport } from './routes/games.$slug'
import { Route as ProfileUsernameRouteImport } from './routes/profile.$username'
import { Route as Char91__componentChar93PreviewSplatRouteImport } from './routes/[__component].preview.$'
import { Route as Char91__mockupChar93PreviewSplatRouteImport } from './routes/[__mockup].preview.$'
import { Route as ApiPublicMcpRouteImport } from './routes/api/public/mcp'
import { Route as ApiPublicV1FacetsRouteImport } from './routes/api/public/v1/facets'
import { Route as ApiPublicV1CollectionsIndexRouteImport } from './routes/api/public/v1/collections/index'
import { Route as ApiPublicV1CollectionsSlugRouteImport } from './routes/api/public/v1/collections/$slug'
import { Route as ApiPublicV1GamesIndexRouteImport } from './routes/api/public/v1/games/index'
import { Route as ApiPublicV1GamesSlugRouteImport } from './routes/api/public/v1/games/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersRoute = DevelopersRouteImport.update({
  id: '/developers',
  path: '/developers',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const EmojiRoute = EmojiRouteImport.update({
  id: '/emoji',
  path: '/emoji',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LicensesRoute = LicensesRouteImport.update({
  id: '/licenses',
  path: '/licenses',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsFullDottxtRoute = LlmsFullDottxtRouteImport.update({
  id: '/llms-full.txt',
  path: '/llms-full.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenapiDotjsonRoute = OpenapiDotjsonRouteImport.update({
  id: '/openapi.json',
  path: '/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const DotwellKnownAgentDotjsonRoute =
  DotwellKnownAgentDotjsonRouteImport.update({
    id: '/.well-known/agent.json',
    path: '/.well-known/agent.json',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedImportSearchRoute =
  AuthenticatedImportSearchRouteImport.update({
    id: '/import-search',
    path: '/import-search',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImportsRoute = AuthenticatedImportsRouteImport.update({
  id: '/imports',
  path: '/imports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyLibraryRoute = AuthenticatedMyLibraryRouteImport.update({
  id: '/my-library',
  path: '/my-library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReviewRoute = AuthenticatedReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesSlugRoute = GamesSlugRouteImport.update({
  id: '/games/$slug',
  path: '/games/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91__componentChar93PreviewSplatRoute =
  Char91__componentChar93PreviewSplatRouteImport.update({
    id: '/__component/preview/$',
    path: '/__component/preview/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91__mockupChar93PreviewSplatRoute =
  Char91__mockupChar93PreviewSplatRouteImport.update({
    id: '/__mockup/preview/$',
    path: '/__mockup/preview/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicMcpRoute = ApiPublicMcpRouteImport.update({
  id: '/api/public/mcp',
  path: '/api/public/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1FacetsRoute = ApiPublicV1FacetsRouteImport.update({
  id: '/api/public/v1/facets',
  path: '/api/public/v1/facets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1CollectionsIndexRoute =
  ApiPublicV1CollectionsIndexRouteImport.update({
    id: '/api/public/v1/collections/',
    path: '/api/public/v1/collections/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1CollectionsSlugRoute =
  ApiPublicV1CollectionsSlugRouteImport.update({
    id: '/api/public/v1/collections/$slug',
    path: '/api/public/v1/collections/$slug',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1GamesIndexRoute = ApiPublicV1GamesIndexRouteImport.update({
  id: '/api/public/v1/games/',
  path: '/api/public/v1/games/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1GamesSlugRoute = ApiPublicV1GamesSlugRouteImport.update({
  id: '/api/public/v1/games/$slug',
  path: '/api/public/v1/games/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/developers': typeof DevelopersRoute
  '/discover': typeof DiscoverRoute
  '/emoji': typeof EmojiRoute
  '/library': typeof LibraryRoute
  '/licenses': typeof LicensesRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/agent.json': typeof DotwellKnownAgentDotjsonRoute
  '/import-search': typeof AuthenticatedImportSearchRoute
  '/imports': typeof AuthenticatedImportsRoute
  '/my-library': typeof AuthenticatedMyLibraryRoute
  '/review': typeof AuthenticatedReviewRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/games/$slug': typeof GamesSlugRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/collections/': typeof CollectionsIndexRoute
  '/__component/preview/$': typeof Char91__componentChar93PreviewSplatRoute
  '/__mockup/preview/$': typeof Char91__mockupChar93PreviewSplatRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/api/public/v1/facets': typeof ApiPublicV1FacetsRoute
  '/api/public/v1/collections/$slug': typeof ApiPublicV1CollectionsSlugRoute
  '/api/public/v1/games/$slug': typeof ApiPublicV1GamesSlugRoute
  '/api/public/v1/collections/': typeof ApiPublicV1CollectionsIndexRoute
  '/api/public/v1/games/': typeof ApiPublicV1GamesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/developers': typeof DevelopersRoute
  '/discover': typeof DiscoverRoute
  '/emoji': typeof EmojiRoute
  '/library': typeof LibraryRoute
  '/licenses': typeof LicensesRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/agent.json': typeof DotwellKnownAgentDotjsonRoute
  '/import-search': typeof AuthenticatedImportSearchRoute
  '/imports': typeof AuthenticatedImportsRoute
  '/my-library': typeof AuthenticatedMyLibraryRoute
  '/review': typeof AuthenticatedReviewRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/games/$slug': typeof GamesSlugRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/collections': typeof CollectionsIndexRoute
  '/__component/preview/$': typeof Char91__componentChar93PreviewSplatRoute
  '/__mockup/preview/$': typeof Char91__mockupChar93PreviewSplatRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/api/public/v1/facets': typeof ApiPublicV1FacetsRoute
  '/api/public/v1/collections/$slug': typeof ApiPublicV1CollectionsSlugRoute
  '/api/public/v1/games/$slug': typeof ApiPublicV1GamesSlugRoute
  '/api/public/v1/collections': typeof ApiPublicV1CollectionsIndexRoute
  '/api/public/v1/games': typeof ApiPublicV1GamesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/developers': typeof DevelopersRoute
  '/discover': typeof DiscoverRoute
  '/emoji': typeof EmojiRoute
  '/library': typeof LibraryRoute
  '/licenses': typeof LicensesRoute
  '/llms-full.txt': typeof LlmsFullDottxtRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/openapi.json': typeof OpenapiDotjsonRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.well-known/agent.json': typeof DotwellKnownAgentDotjsonRoute
  '/_authenticated/import-search': typeof AuthenticatedImportSearchRoute
  '/_authenticated/imports': typeof AuthenticatedImportsRoute
  '/_authenticated/my-library': typeof AuthenticatedMyLibraryRoute
  '/_authenticated/review': typeof AuthenticatedReviewRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/games/$slug': typeof GamesSlugRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/collections/': typeof CollectionsIndexRoute
  '/__component/preview/$': typeof Char91__componentChar93PreviewSplatRoute
  '/__mockup/preview/$': typeof Char91__mockupChar93PreviewSplatRoute
  '/api/public/mcp': typeof ApiPublicMcpRoute
  '/api/public/v1/facets': typeof ApiPublicV1FacetsRoute
  '/api/public/v1/collections/$slug': typeof ApiPublicV1CollectionsSlugRoute
  '/api/public/v1/games/$slug': typeof ApiPublicV1GamesSlugRoute
  '/api/public/v1/collections/': typeof ApiPublicV1CollectionsIndexRoute
  '/api/public/v1/games/': typeof ApiPublicV1GamesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/developers'
    | '/discover'
    | '/emoji'
    | '/library'
    | '/licenses'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/openapi.json'
    | '/sitemap.xml'
    | '/.well-known/agent.json'
    | '/import-search'
    | '/imports'
    | '/my-library'
    | '/review'
    | '/settings'
    | '/collections/$slug'
    | '/games/$slug'
    | '/profile/$username'
    | '/collections/'
    | '/__component/preview/$'
    | '/__mockup/preview/$'
    | '/api/public/mcp'
    | '/api/public/v1/facets'
    | '/api/public/v1/collections/$slug'
    | '/api/public/v1/games/$slug'
    | '/api/public/v1/collections/'
    | '/api/public/v1/games/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/developers'
    | '/discover'
    | '/emoji'
    | '/library'
    | '/licenses'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/openapi.json'
    | '/sitemap.xml'
    | '/.well-known/agent.json'
    | '/import-search'
    | '/imports'
    | '/my-library'
    | '/review'
    | '/settings'
    | '/collections/$slug'
    | '/games/$slug'
    | '/profile/$username'
    | '/collections'
    | '/__component/preview/$'
    | '/__mockup/preview/$'
    | '/api/public/mcp'
    | '/api/public/v1/facets'
    | '/api/public/v1/collections/$slug'
    | '/api/public/v1/games/$slug'
    | '/api/public/v1/collections'
    | '/api/public/v1/games'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/developers'
    | '/discover'
    | '/emoji'
    | '/library'
    | '/licenses'
    | '/llms-full.txt'
    | '/llms.txt'
    | '/openapi.json'
    | '/sitemap.xml'
    | '/.well-known/agent.json'
    | '/_authenticated/import-search'
    | '/_authenticated/imports'
    | '/_authenticated/my-library'
    | '/_authenticated/review'
    | '/_authenticated/settings'
    | '/collections/$slug'
    | '/games/$slug'
    | '/profile/$username'
    | '/collections/'
    | '/__component/preview/$'
    | '/__mockup/preview/$'
    | '/api/public/mcp'
    | '/api/public/v1/facets'
    | '/api/public/v1/collections/$slug'
    | '/api/public/v1/games/$slug'
    | '/api/public/v1/collections/'
    | '/api/public/v1/games/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  DevelopersRoute: typeof DevelopersRoute
  DiscoverRoute: typeof DiscoverRoute
  EmojiRoute: typeof EmojiRoute
  LibraryRoute: typeof LibraryRoute
  LicensesRoute: typeof LicensesRoute
  LlmsFullDottxtRoute: typeof LlmsFullDottxtRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  OpenapiDotjsonRoute: typeof OpenapiDotjsonRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  DotwellKnownAgentDotjsonRoute: typeof DotwellKnownAgentDotjsonRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  GamesSlugRoute: typeof GamesSlugRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  Char91__componentChar93PreviewSplatRoute: typeof Char91__componentChar93PreviewSplatRoute
  Char91__mockupChar93PreviewSplatRoute: typeof Char91__mockupChar93PreviewSplatRoute
  ApiPublicMcpRoute: typeof ApiPublicMcpRoute
  ApiPublicV1FacetsRoute: typeof ApiPublicV1FacetsRoute
  ApiPublicV1CollectionsSlugRoute: typeof ApiPublicV1CollectionsSlugRoute
  ApiPublicV1GamesSlugRoute: typeof ApiPublicV1GamesSlugRoute
  ApiPublicV1CollectionsIndexRoute: typeof ApiPublicV1CollectionsIndexRoute
  ApiPublicV1GamesIndexRoute: typeof ApiPublicV1GamesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers': {
      id: '/developers'
      path: '/developers'
      fullPath: '/developers'
      preLoaderRoute: typeof DevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emoji': {
      id: '/emoji'
      path: '/emoji'
      fullPath: '/emoji'
      preLoaderRoute: typeof EmojiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licenses': {
      id: '/licenses'
      path: '/licenses'
      fullPath: '/licenses'
      preLoaderRoute: typeof LicensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms-full.txt': {
      id: '/llms-full.txt'
      path: '/llms-full.txt'
      fullPath: '/llms-full.txt'
      preLoaderRoute: typeof LlmsFullDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openapi.json': {
      id: '/openapi.json'
      path: '/openapi.json'
      fullPath: '/openapi.json'
      preLoaderRoute: typeof OpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/agent.json': {
      id: '/.well-known/agent.json'
      path: '/.well-known/agent.json'
      fullPath: '/.well-known/agent.json'
      preLoaderRoute: typeof DotwellKnownAgentDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/import-search': {
      id: '/_authenticated/import-search'
      path: '/import-search'
      fullPath: '/import-search'
      preLoaderRoute: typeof AuthenticatedImportSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/imports': {
      id: '/_authenticated/imports'
      path: '/imports'
      fullPath: '/imports'
      preLoaderRoute: typeof AuthenticatedImportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-library': {
      id: '/_authenticated/my-library'
      path: '/my-library'
      fullPath: '/my-library'
      preLoaderRoute: typeof AuthenticatedMyLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/review': {
      id: '/_authenticated/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AuthenticatedReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$slug': {
      id: '/games/$slug'
      path: '/games/$slug'
      fullPath: '/games/$slug'
      preLoaderRoute: typeof GamesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__component/preview/$': {
      id: '/__component/preview/$'
      path: '/__component/preview/$'
      fullPath: '/__component/preview/$'
      preLoaderRoute: typeof Char91__componentChar93PreviewSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__mockup/preview/$': {
      id: '/__mockup/preview/$'
      path: '/__mockup/preview/$'
      fullPath: '/__mockup/preview/$'
      preLoaderRoute: typeof Char91__mockupChar93PreviewSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mcp': {
      id: '/api/public/mcp'
      path: '/api/public/mcp'
      fullPath: '/api/public/mcp'
      preLoaderRoute: typeof ApiPublicMcpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/facets': {
      id: '/api/public/v1/facets'
      path: '/api/public/v1/facets'
      fullPath: '/api/public/v1/facets'
      preLoaderRoute: typeof ApiPublicV1FacetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/collections/': {
      id: '/api/public/v1/collections/'
      path: '/api/public/v1/collections'
      fullPath: '/api/public/v1/collections/'
      preLoaderRoute: typeof ApiPublicV1CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/collections/$slug': {
      id: '/api/public/v1/collections/$slug'
      path: '/api/public/v1/collections/$slug'
      fullPath: '/api/public/v1/collections/$slug'
      preLoaderRoute: typeof ApiPublicV1CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/games/': {
      id: '/api/public/v1/games/'
      path: '/api/public/v1/games'
      fullPath: '/api/public/v1/games/'
      preLoaderRoute: typeof ApiPublicV1GamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/games/$slug': {
      id: '/api/public/v1/games/$slug'
      path: '/api/public/v1/games/$slug'
      fullPath: '/api/public/v1/games/$slug'
      preLoaderRoute: typeof ApiPublicV1GamesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedImportSearchRoute: typeof AuthenticatedImportSearchRoute
  AuthenticatedImportsRoute: typeof AuthenticatedImportsRoute
  AuthenticatedMyLibraryRoute: typeof AuthenticatedMyLibraryRoute
  AuthenticatedReviewRoute: typeof AuthenticatedReviewRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedImportSearchRoute: AuthenticatedImportSearchRoute,
  AuthenticatedImportsRoute: AuthenticatedImportsRoute,
  AuthenticatedMyLibraryRoute: AuthenticatedMyLibraryRoute,
  AuthenticatedReviewRoute: AuthenticatedReviewRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  DevelopersRoute: DevelopersRoute,
  DiscoverRoute: DiscoverRoute,
  EmojiRoute: EmojiRoute,
  LibraryRoute: LibraryRoute,
  LicensesRoute: LicensesRoute,
  LlmsFullDottxtRoute: LlmsFullDottxtRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  OpenapiDotjsonRoute: OpenapiDotjsonRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  DotwellKnownAgentDotjsonRoute: DotwellKnownAgentDotjsonRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  GamesSlugRoute: GamesSlugRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  Char91__componentChar93PreviewSplatRoute:
    Char91__componentChar93PreviewSplatRoute,
  Char91__mockupChar93PreviewSplatRoute: Char91__mockupChar93PreviewSplatRoute,
  ApiPublicMcpRoute: ApiPublicMcpRoute,
  ApiPublicV1FacetsRoute: ApiPublicV1FacetsRoute,
  ApiPublicV1CollectionsSlugRoute: ApiPublicV1CollectionsSlugRoute,
  ApiPublicV1GamesSlugRoute: ApiPublicV1GamesSlugRoute,
  ApiPublicV1CollectionsIndexRoute: ApiPublicV1CollectionsIndexRoute,
  ApiPublicV1GamesIndexRoute: ApiPublicV1GamesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
